import type { Metadata } from 'next';
import type { IAxiosRegister } from '@/lib/types/global';
import type { ChildProps } from '@/lib/types/props';
import { cookies } from 'next/headers';
import axios from '@/lib/axios';
import { Provider, SCRegistry } from '@/lib/components';
import '@/lib/styles/globals.css';

export const metadata: Metadata = {
	title: 'NJShort',
	description: 'Generated by create next app',
};

async function getData() {
	const token = cookies().get('authenticate');

	return token
		? axios({
				url: '/auth/userData',
				headers: { Authorization: token.value }
			}).then(res => res.data)
				.catch(() => null)
		: null;
}

export default async function RootLayout({ children }: ChildProps) {
	const data: IAxiosRegister | null = await getData();

	return (
		<html lang='en'>
			<body>
				<SCRegistry>
					<Provider data={data}>
						{children}
					</Provider>
				</SCRegistry>
			</body>
		</html>
	);
}
